INSERT INTO AGENCIAS VALUES(1,'NASA','EEUU','1930','Victor Bonilla');
INSERT INTO AGENCIAS VALUES(2,'RASS','Rusia','1918','Victor Bonilla');
INSERT INTO AGENCIAS VALUES(3,'CCNAS','China','1980','Victor Bonilla');
INSERT INTO AGENCIAS VALUES(4,'INAS','India','1940','Victor Bonilla');
INSERT INTO AGENCIAS VALUES(5,'GANS','Alemania','1950','Victor Bonilla');


INSERT INTO SATELITES VALUES(1,'Spuznik','20km','2500kg','7500000$');